version: "3.7"

services:
  postgres:
    container_name: resumedb
    image: postgres:14-alpine
    restart: unless-stopped
    ports:
      - "5433:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=12345
      
volumes:
  postgres_volume:
